# -*- coding: utf-8 -*-
"""Generate the handoff briefing for the collaborating AI."""
import csv, os, io, json, collections

DST = r"D:\ai-antigravity\ipas-aiap\verification"
PRAC = r"D:\ai-antigravity\ipas-aiap\practice"
HERE = os.path.dirname(os.path.abspath(__file__))

cor = list(csv.DictReader(open(os.path.join(DST, '07_正確圖片對應.csv'), encoding='utf-8-sig')))
fix = list(csv.DictReader(open(os.path.join(DST, '09_修正版題庫_含正確圖片對應.csv'), encoding='utf-8-sig')))
pdfdata = json.load(open(os.path.join(HERE, 'pdf_extracted.json'), encoding='utf-8'))
s = json.load(open(os.path.join(HERE, 'final.json'), encoding='utf-8'))

correct = {r['編號'] for r in cor}
grp = {r['編號'] for r in cor if r['題組']}
orig = {os.path.splitext(f)[0] for f in os.listdir(os.path.join(PRAC, 'assets', 'q_images'))
        if '_p' not in f and f[:2] in ('A1', 'A2', 'B1', 'B2', 'B3')}
over = sorted(orig - correct)
under = sorted(correct - orig)
pending = [r for r in fix if r['圖片待人工確認'] == '是']

groups = []
for pdfname, v in pdfdata.items():
    for g in v.get('groups', []):
        groups.append((pdfname, g['first'], g['last'], len(g['shared_images'])))

L = []; w = L.append
w('# 交接說明：iPAS 題庫圖片對應修正（給協作 AI）')
w('')
w('> 本文件自足，不需其他對話脈絡。所有結論皆可用文中方法自行驗證。  ')
w('> 資料根目錄：`D:\\ai-antigravity\\ipas-aiap\\`  ')
w('> **本版取代先前版本**，內容有實質修正，見第 1 節。')
w('')
w('## 0. 先讀這段')
w('')
w('`practice/` 目前的 `圖片檔名` 欄**已經是我上一版的輸出，但那一版是錯的**，請再換一次。')
w('')
w('原因：官方 PDF 有**題組**結構——一段共用情境敘述加共用附圖，套用到一整個題號範圍')
w('（例如「請根據下述資料情境回答 43~47 題」）。我上一版不知道題組存在，')
w('我上一版把 19 題判成「錯配」而清空，其中 **3 題判錯**——`B2-098`、`B3-092`、`B3-093` '
  '屬於題組，確實需要共用圖；另外 16 題判斷正確。')
w('')
w(f'此外上一版**漏掉了 10 題題組成員**的共用圖：'
  '`B2-044`、`B2-045`、`B2-046`、`B2-048`、`B3-042`、`B3-043`、`B3-044` 等。')
w('')
w(f'正確答案是 **{len(correct)} 題需要顯示附圖**，其中 **{len(grp)} 題是靠題組共用圖**。')
w('')
w('---')
w('')
w('## 1. 三個版本的差異')
w('')
w('| 版本 | 標記題數 | 狀態 |')
w('| --- | ---: | --- |')
w(f'| 原始版（`assets/q_images/` 的檔名） | {len(orig)} | ❌ 一張圖被複製給相鄰多個題號 |')
w('| 我的上一版（目前在 `practice/` 的 CSV） | 37 | ❌ 去掉了重複，但不懂題組，砍掉了該保留的共用圖 |')
w(f'| **本版（題組感知）** | **{len(correct)}** | ✅ 每張圖來自 PDF 座標歸屬，題組共用圖指派給全組 |')
w('')
w('相對於原始版：')
w('')
w(f'- **多標了 {len(over)} 題**（PDF 中確實沒有圖，也不屬於任何題組）：')
w('  ' + '、'.join(f'`{x}`' for x in over))
w(f'- **漏標了 {len(under)} 題**：')
w('  ' + '、'.join(f'`{x}`' for x in under))
w('')
w('---')
w('')
w('## 2. 題組結構（本次的關鍵）')
w('')
w(f'4 份中級 PDF 共有 **{len(groups)} 個題組**，涵蓋 **{sum(b-a+1 for _,a,b,_ in groups)} 題**：')
w('')
w('| PDF | 題組 | 共用圖數 |')
w('| --- | :---: | ---: |')
for pdfname, a, b, n in groups:
    short = pdfname.replace('AI應用規劃師', '').replace('(當次試題公告114', '')[:30]
    w(f'| `{short}…` | 第 {a}~{b} 題 | {n} |')
w('')
w('**題組的陷阱**：共用敘述與附圖的實體位置在「前一題的最後一個選項之後、該組第一題的題號之前」。')
w('若用「圖片落在哪一題的文字範圍內」來歸屬，這些圖會被算給**前一題**或變成無人認領的孤兒。')
w('必須先偵測題組範圍，再把該區段的圖指派給整組。')
w('')
w('偵測方式：在全文中搜尋 `(\\d{1,2})\\s*[-–—~～至到]\\s*(\\d{1,2})\\s*題`。')
w('注意官方用語不統一，「請回答**最後**48-50題」「請根據下述資料情境回答**以**43~47題」')
w('中間會插字，所以**不能**要求「回答」二字緊接數字。')
w('')
w('---')
w('')
w('## 3. 原始版的 bug（仍需了解，避免重蹈）')
w('')
w('原始版 46 個檔案裡只有 22 張是不重複的內容——一張圖被複製給相鄰題號。例如：')
w('')
w('```')
w('practice/assets/q_images/B2-001.jpeg')
w('practice/assets/q_images/B2-002.jpeg   四個檔案位元組完全相同')
w('practice/assets/q_images/B2-003.jpeg   md5 皆為 1d92bdca…')
w('practice/assets/q_images/B2-004.jpeg')
w('```')
w('')
w('該圖是一張左偏密度分佈圖，只屬於 `B2-003`「附圖為某資料之分佈圖，此圖資料之偏態值…」。')
w('B2-001（Z 分數意涵）、B2-002（pandas 語法）、B2-004（CDF 定義）都不需要它，')
w('且這三題不屬於任何題組。')
w('')
w('`B3-038`～`B3-041` 則是四題**各有不同的**程式碼截圖卻共用一檔：')
w('')
w('- `B3-038`「附圖程式碼所計算的是哪一類型的評估指標？」→ `sum((y_true-y_pred)**2)/len(y_true)`（MSE）')
w('- `B3-039`「附圖程式碼實現的是哪一種正則化技術？」→ `mask = np.random.binomial(...)`（Dropout）')
w('')
w('---')
w('')
w('## 4. 我提供的檔案')
w('')
w('| 檔案 | 內容 |')
w('| --- | --- |')
w('| `verification/09_修正版題庫_含正確圖片對應.csv` | **直接取代 `practice/` 的題庫**：600 列，新增 `題組`、`圖片待人工確認` 欄 |')
w(f'| `verification/figures/` | {len(os.listdir(os.path.join(DST,"figures")))} 張圖（3× 解析度 PNG） |')
w(f'| `verification/07_正確圖片對應.csv` | {len(correct)} 題的正確歸屬，分「共用圖／自有圖」兩欄 |')
w('| `verification/08_現況圖片對應稽核.csv` | 逐題稽核 |')
w('| `verification/pdf_extracted.json` | 600 題結構化原文，含題組、座標、圖片 bbox |')
w('')
w('### 檔名規則')
w('')
w('- `G_<該組第一題編號>.png` — 題組共用圖，組內每一題都引用同一個檔')
w('- `<編號>.png` — 該題自有的圖')
w('- 跨頁時加 `_p<頁碼>`，例如 `G_B2-043_p13.png`、`G_B2-043_p14.png`')
w('- `圖片檔名` 欄以 `;` 分隔多檔，**共用圖在前、自有圖在後**，前端需依序渲染')
w('')
w('### 套用')
w('')
w('```bash')
w('cp -r verification/figures practice/figures')
w('cp verification/09_修正版題庫_含正確圖片對應.csv practice/FALO-IPAS-AIAP-20260802.csv')
w('```')
w('')
w('`v3.01_image_demo.html` 的 `processData` 會把任何路徑改寫成 `images/<basename>`，')
w('且只取單一檔名。套用新表要一併改成支援 `;` 多檔並保留 `figures/` 路徑。')
w('頁面上寫死的「共 52 題」也需更新為實際筆數。')
w('')
w('---')
w('')
w('## 5. 歸屬方法（供驗證或重做）')
w('')
w('1. PyMuPDF 逐頁取 `page.get_text("blocks")`，濾除頁首頁尾。')
w('2. 以「答案字母 + 題號」樣式切題，記錄每題的 `(頁, y)` 起點。')
w('   起點要取 regex 的 **match.end()**；樣式以 `(?:^|\\n)` 開頭，`match.start()` 會落在前一個區塊裡。')
w('3. 每題認領的範圍是「本題起點 → **下一題起點**」，不是「本題最後一個文字區塊」。')
w('   否則落在最後一個選項之後的圖會變成孤兒。')
w('4. 偵測題組範圍，把「題組宣告位置 → 該組第一題起點」之間的圖指派給全組，')
w('   並從原持有者移除。')
w('5. **先濾浮水印**：出現在 ≥60% 頁面且尺寸位置固定的圖（本題庫為 1084×454，'
  '固定於 `(102.5,365)-(492.75,528.8)`）。沒濾掉會讓幾乎每題都「有圖」。')
w('')
w('**完整性檢查**：把 12 份 PDF 的非浮水印圖全部列出，確認每一張都被某題認領。')
w('目前 **72 張全數認領，0 張孤兒**。這是驗證歸屬正確性最有效的單一指標。')
w('')
w('可運作的實作在 `verification/extract.py`。')
w('')
w('---')
w('')
w('## 6. 仍需人工的部分')
w('')
w(f'我只能偵測**內嵌點陣圖**。若附圖是 PDF 向量繪製（線條、表格框），我抓不到。')
w(f'這類有 **{len(pending)} 題**，已在 `09` 的 `圖片待人工確認` 欄標為「是」。')
w('')
w('`verification/06_圖片題人工校對台.html` 是為此做的工具：逐題並列 PDF 原始版面渲染圖與 CSV 現況。')
w('（注意：該工具建立於題組修正之前，`Tier` 分級未含題組概念，但原始版面渲染圖仍然正確可用。）')
w('')
w('---')
w('')
w('## 7. 題庫的其他問題（與圖片無關）')
w('')
w('完整結果見 `verification/01_檢查表.md`。摘要：')
w('')
w('| 問題 | 題數 | 嚴重度 |')
w('| --- | ---: | --- |')
w('| 標準答案錯誤（`B1-034` 應為 4，現為 3） | 1 | 🔴 致命 |')
w('| PDF 頁首文字混入題幹／選項中間 | 71 | 🔴 嚴重 |')
w('| 題幹／選項遭刪節，情境與條件遺失 | 47 | 🔴 嚴重 |')
w('| 文字改寫（非逐字轉錄） | 21 | 🟠 高 |')
w('| 簡體字、數學式遺失（`A1-017`、`B2-016`） | 6 | 🟡 中 |')
w('| `題號` 欄語意不統一、`文件名稱` 對不到實體檔 | 350 | 🟡 中 |')
w('')
w(f"600 題中 {s['content']['PASS']} 題（{s['content']['PASS']/6:.1f}%）題幹與選項語意與官方 PDF 相符。")
w('逐題明細在 `verification/02_逐題檢查明細.csv`。正確內容都可從 `pdf_extracted.json` 取得。')
w('')
w('---')
w('')
w('## 8. 重抽 PDF 前先看這段')
w('')
w('12 份官方 PDF 有四種互不相容的版面變體，只處理一種會漏抽大量題目：')
w('')
w('1. 答案字母**混用全形與半形**（`C` 與 `Ｃ`）')
w('2. 題號後**有時沒有句點**（同一份 PDF 前 10 題有、第 11 題起沒有）')
w('3. 答案字母**有時與題號同一行**（`Ｂ 40 請參考附圖…`）')
w('4. 頁首「答案／題目」在不同 PDF 中是**一個區塊**、**直排三個區塊**，'
  '或**中途左右對調**（`答案題目` 10 頁 → `題目答案` 8 頁）')
w('')
w('第 4 點是現行題庫那 71 題頁首雜訊的成因。濾頁首請用')
w('「同一份 PDF 內出現率 ≥35% 的短區塊即為樣板」自動偵測，不要寫死字串。')

io.open(os.path.join(DST, '10_給協作AI的交接說明.md'), 'w', encoding='utf-8').write('\n'.join(L))
print('wrote, lines =', len(L))
