# -*- coding: utf-8 -*-
"""Generate the handoff briefing for the collaborating AI."""
import csv, os, io, json, collections

DST = r"D:\ai-antigravity\ipas-aiap\verification"
HERE = os.path.dirname(os.path.abspath(__file__))

rep = list(csv.DictReader(open(os.path.join(DST, '08_現況圖片對應稽核.csv'), encoding='utf-8-sig')))
cor = list(csv.DictReader(open(os.path.join(DST, '07_正確圖片對應.csv'), encoding='utf-8-sig')))
fix = list(csv.DictReader(open(os.path.join(DST, '09_修正版題庫_含正確圖片對應.csv'), encoding='utf-8-sig')))
s = json.load(open(os.path.join(HERE, 'final.json'), encoding='utf-8'))

miss = [r for r in rep if r['判定'].startswith('❌ 遺漏')]
wrong = [r for r in rep if r['判定'].startswith('❌ 錯配')]
shared = [r for r in rep if r['判定'].startswith('⚠️')]
okk = [r for r in rep if r['判定'].startswith('✅')]
pending = [r for r in fix if r['圖片待人工確認'] == '是']

L = []; w = L.append
w('# 交接說明：iPAS 題庫圖片對應修正（給協作 AI）')
w('')
w('> 本文件自足，不需要其他對話脈絡。所有結論都可用文中方法自行驗證。  ')
w('> 資料根目錄：`D:\\ai-antigravity\\ipas-aiap\\`')
w('')
w('## 0. 一句話')
w('')
w(f'`practice/FALO-IPAS-AIAP-20260802.csv` 的 `圖片檔名` 欄有 46 筆標記，'
  f'其中**只有 {len(okk)} 筆確定正確**；另有 {len(miss)} 題該有圖卻沒標。'
  f'我已重建正確對應，放在 `verification/09_修正版題庫_含正確圖片對應.csv`。')
w('')
w('---')
w('')
w('## 1. Bug 與根因')
w('')
w('**症狀**：練習頁 `practice/v3.01_image_demo.html` 上多題顯示的附圖與題目無關。')
w('')
w('**根因**：一張圖被指派給**相鄰的多個題號**，而非該圖實際所屬的那一題。')
w('46 筆標記指向的檔案裡，只有 22 張是不重複的內容——37 題與別題共用同一張圖。')
w('')
w('**最直接的證據**（可自行核對）：')
w('')
w('```')
w('practice/assets/q_images/B2-001.jpeg')
w('practice/assets/q_images/B2-002.jpeg   ← 這四個檔案')
w('practice/assets/q_images/B2-003.jpeg   ← 位元組完全相同')
w('practice/assets/q_images/B2-004.jpeg   ← md5 皆為 1d92bdca…')
w('```')
w('')
w('該圖是一張**左偏密度分佈圖**，只屬於 `B2-003`：')
w('')
w('| 題號 | 題幹 | 需要這張圖嗎 |')
w('| --- | --- | :---: |')
w('| B2-001 | 若某數據點的 Z 分數（Z-Score）= 2，請問代表下列哪一種意涵？ | ❌ |')
w('| B2-002 | 使用 pandas 計算「總銷售額」敘述性統計量應使用哪種語法？ | ❌ |')
w('| **B2-003** | **附圖為某資料之分佈圖，此圖資料之偏態值較有可能為下列哪個選項？** | ✅ |')
w('| B2-004 | 累積分佈函數（CDF）的數學定義為下列何者？ | ❌ |')
w('')
w('**更嚴重的一類**：`B3-038`～`B3-041` 這四題在 PDF 中**各自有不同的程式碼截圖**')
w('（尺寸分別為 444×56、861×230、567×248、810×415＋813×103），卻全被指派同一個檔，')
w('所以這組至多一題正確。已驗證：')
w('')
w('- `B3-038`「附圖程式碼所計算的是哪一類型的評估指標？」→ 圖為 `sum((y_true-y_pred)**2)/len(y_true)`（MSE）')
w('- `B3-039`「附圖程式碼實現的是哪一種正則化技術？」→ 圖為 `mask = np.random.binomial(...)`（Dropout）')
w('')
w('兩張圖內容完全不同，證明必須逐題歸屬。')
w('')
w('---')
w('')
w('## 2. 稽核結果')
w('')
w('| 判定 | 題數 | 說明 |')
w('| --- | ---: | --- |')
w(f'| ✅ 專屬檔案、對應正確 | {len(okk)} | 保留 |')
w(f'| ⚠️ 與其他題共用同一檔 | {len(shared)} | 至多一題正確，其餘須清除或改指向 |')
w(f'| ❌ 錯配：PDF 中根本沒有圖 | {len(wrong)} | 應清空 |')
w(f'| ❌ 遺漏：PDF 有圖卻未標記 | {len(miss)} | 應補上 |')
w('')
w(f'**PDF 實際有內嵌圖的題目共 {len(cor)} 題、{sum(int(r["圖片數"]) for r in cor)} 張圖。**')
w('')
w(f'### 2.1 錯配清單（{len(wrong)} 題，PDF 中沒有任何圖片）')
w('')
w('| 編號 | 現況誤掛檔案 | 題幹 |')
w('| --- | --- | --- |')
for r in wrong:
    w(f"| {r['編號']} | `{r['現況圖片檔']}` | {r['題幹'][:46]}… |")
w('')
w(f'### 2.2 遺漏清單（{len(miss)} 題，PDF 有圖但沒標）')
w('')
w('> 這些多是「請參考附圖…」型題目，**沒有圖就完全無法作答**，優先補。')
w('')
w('| 編號 | 應對應的圖 | 題幹 |')
w('| --- | --- | --- |')
for r in miss:
    w(f"| {r['編號']} | `figures/{r['正確圖片檔']}` | {r['題幹'][:46]}… |")
w('')
w(f'### 2.3 共用同檔清單（{len(shared)} 題）')
w('')
w('| 編號 | 與哪些題共用同一檔 |')
w('| --- | --- |')
seen = set()
for r in shared:
    grp = r['共用此檔的題號']
    if grp in seen:
        continue
    seen.add(grp)
    w(f"| {grp} | 共 {len(grp.split('、'))} 題共用一張圖 |")
w('')
w('---')
w('')
w('## 3. 我提供的檔案')
w('')
w('| 檔案 | 內容 |')
w('| --- | --- |')
w(f'| `verification/09_修正版題庫_含正確圖片對應.csv` | **可直接取代現行題庫**：600 列，`圖片檔名` 欄已修正，另加 `圖片待人工確認` 欄 |')
w(f'| `verification/figures/` | {len(os.listdir(os.path.join(DST,"figures")))} 張逐題裁切圖（3× 解析度，PNG） |')
w(f'| `verification/07_正確圖片對應.csv` | {len(cor)} 題的正確歸屬，含 PDF 檔名、題號、圖片數 |')
w(f'| `verification/08_現況圖片對應稽核.csv` | 56 筆逐題稽核，標明每筆錯在哪 |')
w('')
w('### 套用方式')
w('')
w('```bash')
w('# 1. 複製圖檔')
w('cp -r verification/figures practice/figures')
w('# 2. 換掉題庫（09 的 圖片檔名 欄格式為 "figures/<編號>.png"）')
w('cp verification/09_修正版題庫_含正確圖片對應.csv practice/FALO-IPAS-AIAP-20260802.csv')
w('```')
w('')
w('多圖題（如 `B3-045`）的 `圖片檔名` 以 `;` 分隔多個檔名，前端需支援渲染多張。')
w('')
w('`v3.01_image_demo.html` 目前的路徑處理會把任何路徑改寫成 `images/<basename>`')
w('（見 `processData` 的 `imgUrl` 組法），套用新表時要一併調整，否則會指向錯誤目錄。')
w('另外頁面上寫死的「共 52 題」字樣與實際筆數不符，也需更新。')
w('')
w('---')
w('')
w('## 4. 我的歸屬方法（供你驗證或重做）')
w('')
w('圖片歸屬**不是按頁分配**，而是按**座標包含關係**：')
w('')
w('1. 用 PyMuPDF 逐頁取 `page.get_text("blocks")`，濾除頁首頁尾。')
w('2. 以「答案字母 + 題號」的樣式切出每一題，記錄該題在頁面上的垂直範圍 `y_start`～`y_end`。')
w('3. 對每張圖片取 `page.get_image_bbox()`，若其 bbox 落在某題的垂直範圍內，即屬於該題。')
w('4. **必須先濾除浮水印**：出現在 ≥60% 頁面、且尺寸與位置固定的圖（本題庫為 1084×454，'
  '固定在 `(102.5, 365)–(492.75, 528.8)`）是浮水印，不是題目附圖。沒濾掉會讓幾乎每題都「有圖」。')
w('')
w('結構化結果在 `verification/pdf_extracted.json`（600 題，含題幹、選項、答案、頁碼、座標、圖片 bbox），')
w('可直接使用，不必重寫解析器。')
w('')
w('---')
w('')
w('## 5. 已知限制（需人工，勿自動猜）')
w('')
w(f'我只能偵測**內嵌點陣圖**。若某題的圖是 PDF 向量繪製（線條、表格框），我抓不到。')
w(f'這類有 **{len(pending)} 題**（題文提到「圖／表／程式碼」但無點陣圖），已在 `09` 的 '
  f'`圖片待人工確認` 欄標記為「是」。')
w('')
w('例：`B2-098`（StandardScaler 標準化）現況被掛了一張 iris 程式碼圖，但那張其實屬於 `B2-099`；'
  'B2-098 是否另有向量圖需人工確認。')
w('')
w('`verification/06_圖片題人工校對台.html` 是為此做的工具：逐題並列 PDF 原始版面渲染圖與 CSV 現況，'
  '可直接判定並匯出。用它處理這 %d 題。' % len(pending))
w('')
w('---')
w('')
w('## 6. 題庫還有其他未修的問題')
w('')
w('圖片只是其中一項。完整檢查結果見 `verification/01_檢查表.md`，摘要：')
w('')
w('| 問題 | 題數 | 嚴重度 |')
w('| --- | ---: | --- |')
w('| 標準答案錯誤（`B1-034` 應為 4，現為 3） | 1 | 🔴 致命 |')
w('| PDF 頁首文字混入題幹／選項中間 | 71 | 🔴 嚴重 |')
w('| 題幹／選項遭刪節，情境與條件遺失 | 47 | 🔴 嚴重 |')
w('| 文字改寫（非逐字轉錄） | 22 | 🟠 高 |')
w('| 簡體字、數學式遺失（`A1-017`、`B2-016`） | 6 | 🟡 中 |')
w('| `題號` 欄語意不統一、`文件名稱` 對不到實體檔 | 350 | 🟡 中 |')
w('')
w('逐題明細在 `verification/02_逐題檢查明細.csv`（600 列，含 5 個判定欄）。')
w('這些的正確內容都可從 `pdf_extracted.json` 取得。')
w('')
w('---')
w('')
w('## 7. 若你要重抽 PDF，先看這段')
w('')
w('12 份官方 PDF 有四種互不相容的版面變體，只處理其中一種會漏抽大量題目：')
w('')
w('1. 答案字母**混用全形與半形**（`C` 與 `Ｃ`）')
w('2. 題號後**有時沒有句點**（同一份 PDF 前 10 題有、第 11 題起沒有）')
w('3. 答案字母**有時與題號同一行**（`Ｂ 40 請參考附圖…`）')
w('4. 頁首「答案／題目」在不同 PDF 中是**一個區塊**、**直排三個區塊**，'
  '或**中途左右對調**（`答案題目` 10 頁 → `題目答案` 8 頁）')
w('')
w('第 4 點是現行題庫那 71 題頁首雜訊的成因。濾頁首請用'
  '「同一份 PDF 內出現率 ≥35% 的短區塊即為樣板」自動偵測，不要寫死字串。')
w('')
w('可運作的實作在 `verification/extract.py`。')

io.open(os.path.join(DST, '10_給協作AI的交接說明.md'), 'w', encoding='utf-8').write('\n'.join(L))
print('wrote 10_給協作AI的交接說明.md,', len(L), 'lines')
